# This file defines a Kubernetes Deployment and Service for a web application.

# The Deployment manages the deployment of the web application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment # Name of the deployment
  labels:
    app: webapp # Label to identify the deployment
spec:
  replicas: 1 # Number of pod replicas to run
  selector:
    matchLabels:
      app: webapp # Selector to match the pods with the label 'app: webapp'
  template:
    metadata:
      labels:
        app: webapp # Label for the pods created by this deployment
    spec:
      containers:
        - name: webapp
          image: nanajanashia/k8s-demo-app:v1.0
          ports:
            - containerPort: 3000 # Port that the container listens on
          env:
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret # Reference to a Kubernetes Secret for the MongoDB username
                  key: mongo-user
            - name: USER_PWD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret # Reference to a Kubernetes Secret for the MongoDB password
                  key: mongo-password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-config # Reference to a Kubernetes ConfigMap for the MongoDB URL
                  key: mongo-url
---
# The Service exposes the web application to the outside world.
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort # Type of service, NodePort exposes the service on a static port on each node
  selector:
    app: webapp # Selector to match the pods with the label 'app: webapp'
  ports:
    - protocol: TCP # Protocol used by the service
      port: 3000 # Port on which the service is exposed
      targetPort: 3000 # Port on which the application is running inside the container
      nodePort: 30100 # Static port on each node to expose the service (range: 30000-32767)
